# Generated by Django 3.2.4 on 2022-09-26 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220923_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(910000000), django.core.validators.MaxValueValidator(969999999)]),
        ),
    ]
