# Generated by Django 3.2.4 on 2022-09-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220926_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
