# Generated by Django 3.2.4 on 2022-10-07 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='accounts.category'),
        ),
    ]
